GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "ayo coba2",
  "author": "ilhamosaurus",
  "url": "instagram.com/ilhamosaurus",
  "likes": 302
}

###
GET http://localhost:3003/api/blogs/65c711156f84c5575489c768

###
DELETE http://localhost:3003/api/blogs/65c8ef4eb759903282a5c0a9
