GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "ayo coba2",
  "author": "ilhamosaurus",
  "url": "instagram.com/ilhamosaurus",
  "likes": 302
}

###
GET http://localhost:3003/api/blogs/65c711156f84c5575489c768

###
PUT http://localhost:3003/api/blogs/65c9964c3b448a3c9ec793f6
Content-Type: application/json

{
  "title": "ayo coba lagi",
  "author": "ilhamosaurus",
  "url": "github.com/ilhamosaurus",
  "likes": 400
}
###
DELETE http://localhost:3003/api/blogs/65c9964c3b448a3c9ec793f6
